backend:
  name: git-gateway
  repo: ttngocthao/gatsby-nelifyCMS-template
  branch: master
media_folder: /public/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: "src/pages/blog"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { name: title, label: Title }

  - name: pages
    label: Pages

    files:
      - file: src/pages/index.md
        label: Home Page
        name: homePage
        media_folder: ""
        public_folder: ""
        fields:
          - {
              name: "templateKey",
              widget: hidden,
              label: "Template Key",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Grid Image 1, name: image01, widget: image }
          - { label: Grid Image 2, name: image02, widget: image }
          - { label: Grid Image 3, name: image03, widget: image }
          - { label: Grid Image 4, name: image04, widget: image }
          - {
              label: Short Intro,
              name: shortIntro,
              widget: object,
              fields:
                {
                  name: shortIntroHeading,
                  label: Short Intro Heading,
                  widget: string,
                  required: false,
                },
              {
                name: shortIntroText,
                label: Short Intro Text,
                widget: list,
                fields:
                  [
                    {
                      name: paragraph,
                      label: paragraph,
                      widget: string,
                      required: false,
                    },
                  ],
              },
            }
          - {
              label: Products Intro,
              name: productsIntro,
              widget: object,
              fields:
                {
                  name: productIntroHeading,
                  label: product Intro Title,
                  required: false,
                  widget: string,
                },
              {
                name: shortProductsIntroText,
                label: Short Products Intro Text,
                widget: list,
                fields:
                  [
                    {
                      name: paragraph,
                      label: paragraph,
                      widget: string,
                      required: false,
                    },
                  ],
              },
            }
      - file: src/pages/products/index.md
        label: Products Page
        name: productsPage
        media_folder: ""
        public_folder: ""
        fields:
          - {
              name: "templateKey",
              widget: hidden,
              label: "Template Key",
              default: "products-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
