backend:
  name: git-gateway
  repo: ttngocthao/gatsby-nelifyCMS-template
  branch: master
media_folder: /public/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    folder: "src/pages/blog"
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { name: title, label: Title }

  - name: pages
    label: Pages

    files:
      - file: src/pages/index.md
        label: Home Page
        name: homePage
        media_folder: ""
        public_folder: ""
        fields:
          - {
              name: "templateKey",
              widget: hidden,
              label: "Template Key",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Grid Image 1, name: image01, widget: image }
          - { label: Grid Image 2, name: image02, widget: image }
          - { label: Grid Image 3, name: image03, widget: image }
          - { label: Grid Image 4, name: image04, widget: image }

          - {
              label: Short Intro,
              name: shortIntro,
              widget: object,
              fields:
                [
                  {
                    name: heading,
                    label: Short Intro Heading,
                    widget: string,
                    required: false,
                  },
                  {
                    name: text,
                    label: Short Intro Text,
                    widget: list,
                    fields:
                      [
                        {
                          name: paragraph,
                          label: paragraph,
                          widget: string,
                          required: false,
                        },
                      ],
                  },
                ],
            }

          - {
              label: Products Intro,
              name: productsIntro,
              widget: object,
              fields:
                [
                  {
                    name: heading,
                    label: product Intro Title,
                    required: false,
                    widget: string,
                  },
                  {
                    name: text,
                    label: Short Products Intro Text,
                    widget: list,
                    fields:
                      [
                        {
                          name: paragraph,
                          label: paragraph,
                          widget: string,
                          required: false,
                        },
                      ],
                  },
                ],
            }
          - {
              label: About Section,
              name: aboutDetail,
              widget: object,
              fields:
                [
                  { name: avatar, label: profile Image, widget: image },
                  { name: role, label: your role, widget: string },
                  {
                    name: story,
                    label: your story paragraphs,
                    widget: list,
                    fields:
                      [
                        {
                          name: block,
                          label: block of texts,
                          widget: list,
                          fields:
                            [{ name: paragraph, label: text, widget: string }],
                        },
                        {
                          name: image,
                          label: image for this block,
                          widget: image,
                          required: false,
                        },
                      ],
                  },
                ],
            }
          - {
              label: Products Section,
              name: products,
              widget: object,
              fields:
                [
                  {
                    name: delieveryInfo,
                    label: Delievery Information,
                    widget: list,
                    fields:
                      [{ name: paragraph, label: paragraph, widget: string }],
                  },
                  {
                    name: shortIntro,
                    label: Short Introduction,
                    widget: list,
                    fields:
                      [{ name: paragraph, label: paragraph, widget: string }],
                  },
                  {
                    name: productList,
                    label: Products,
                    widget: list,
                    fields:
                      [
                        {
                          name: productName,
                          label: Product name,
                          widget: string,
                          required: false,
                        },
                        {
                          name: productCode,
                          label: Product code/id to identify,
                          widget: string,
                          required: false,
                        },
                        {
                          name: productPrice,
                          label: Product price,
                          widget: string,
                        },
                        {
                          name: productImages,
                          label: Product images,
                          widget: list,
                          fields:
                            [
                              {
                                name: productImage,
                                label: Product Image,
                                widget: image,
                              },
                              {
                                name: productImageCap,
                                label: Product Image Caption,
                                widget: string,
                                required: false,
                              },
                            ],
                        },
                        {
                          name: productDescription,
                          label: Product description,
                          widget: list,
                          fields:
                            [
                              {
                                name: paragraph,
                                label: paragraph,
                                widget: string,
                              },
                            ],
                          required: false,
                        },
                        {
                          name: productMoreDetail,
                          label: Product more details,
                          widget: list,
                          fields:
                            [
                              {
                                name: paragraph,
                                label: paragraph,
                                widget: string,
                              },
                            ],
                          required: false,
                        },
                      ],
                  },
                ],
            }
      - file: src/pages/products/index.md
        label: Products Page
        name: productsPage
        media_folder: ""
        public_folder: ""
        fields:
          - {
              name: "templateKey",
              widget: hidden,
              label: "Template Key",
              default: "products-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
